
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mongo
  
  node:
    container_name: node
    build: 
      context: ./backend/
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  
  front:
    container_name: front
    build: 
      context: ./frontend/
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - "3000:3000"